# Generated by Django 5.0.6 on 2024-05-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlike',
            name='status',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='status',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
